# Generated by Django 4.2.2 on 2023-06-24 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idCategory', models.IntegerField(primary_key=True, serialize=False)),
                ('nameCategory', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('idProduct', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('img_url', models.ImageField(upload_to='imagenesProducto')),
                ('fec_agregar', models.DateField(auto_now_add=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosko.category')),
            ],
        ),
    ]
