# Generated by Django 4.2.2 on 2023-06-24 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosko', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fec_agregar',
            new_name='fecADD',
        ),
    ]
